site_name: TickLab
theme:
  name: material
  favicon: assets/faviconTickLab.png
  logo: assets/logoTickLab.svg
  palette:
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
